name: Django test
on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        id: cache-dep
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r app/requirements/dev.txt
      - name: lint
        working-directory: ./app
        run: |
          flake8
          isort --check-only --diff .
          black . --check --diff
          python manage.py makemigrations --check --dry-run
      - name: Django app test
        id: django_tests
        working-directory: ./app
        run: |
          python manage.py test --parallel --settings=config.tests